// Package api_models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api_models

// Car defines model for Car.
type Car struct {
	Color *string `json:"color,omitempty"`
	Id    string  `json:"id"`
	Name  string  `json:"name"`
}

// CreateCarRequest defines model for CreateCarRequest.
type CreateCarRequest struct {
	Color *string `json:"color,omitempty"`
	Name  string  `json:"name"`
}

// CreateCarJSONRequestBody defines body for CreateCar for application/json ContentType.
type CreateCarJSONRequestBody = CreateCarRequest
