// Package api_models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api_models

import (
	"time"
)

// Brand defines model for Brand.
type Brand struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Car defines model for Car.
type Car struct {
	Brand       *Brand    `json:"brand,omitempty"`
	Color       *Color    `json:"color,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// CarBrand Brand reference.
// Resolution order:
// 1. id
// 2. name
// Examples:
// Existing name:
//
//	{
//	  "id": "uuid"
//	}
//
// Find or create by name:
//
//	{
//	  "name": "BMW"
//	}
//
// Clear brand in PATCH:
//
//	{}
type CarBrand struct {
	Id   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// CarColor Color reference.
// Resolution order:
// 1. id
// 2. code
// Examples:
// Existing color:
//
//	{
//	  "id": "uuid"
//	}
//
// Find or create by code:
//
//	{
//	  "code": "red"
//	}
//
// Clear color in PATCH:
//
//	{}
type CarColor struct {
	Code *string `json:"code,omitempty"`
	Id   *string `json:"id,omitempty"`
}

// Color defines model for Color.
type Color struct {
	Code string `json:"code"`
	Id   string `json:"id"`
}

// CreateBrandRequest defines model for CreateBrandRequest.
type CreateBrandRequest struct {
	Name string `json:"name"`
}

// CreateCarRequest defines model for CreateCarRequest.
type CreateCarRequest struct {
	// Brand Brand reference.
	// Resolution order:
	// 1. id
	// 2. name
	// Examples:
	// Existing name:
	//   {
	//     "id": "uuid"
	//   }
	// Find or create by name:
	//   {
	//     "name": "BMW"
	//   }
	// Clear brand in PATCH:
	//   {}
	Brand *CarBrand `json:"brand,omitempty"`

	// Color Color reference.
	// Resolution order:
	// 1. id
	// 2. code
	// Examples:
	// Existing color:
	//   {
	//     "id": "uuid"
	//   }
	// Find or create by code:
	//   {
	//     "code": "red"
	//   }
	// Clear color in PATCH:
	//   {}
	Color       *CarColor `json:"color,omitempty"`
	Description *string   `json:"description,omitempty"`
	Name        string    `json:"name"`
}

// CreateColorRequest defines model for CreateColorRequest.
type CreateColorRequest struct {
	Code string `json:"code"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Database Example: ok
	Database string `json:"database"`

	// Status Example: ok
	Status string `json:"status"`

	// Version Example: 1.0.6
	Version string `json:"version"`
}

// UpdateBrandRequest defines model for UpdateBrandRequest.
type UpdateBrandRequest struct {
	Name *string `json:"name,omitempty"`
}

// UpdateCarRequest defines model for UpdateCarRequest.
type UpdateCarRequest struct {
	// Brand Brand update rules:
	// field omitted:
	//   brand is not changed
	// brand: {}
	//   clears current brand
	// brand.id:
	//   uses existing brand
	// brand.name:
	//   finds existing brand by name or creates new one
	Brand *CarBrand `json:"brand,omitempty"`

	// Color Color update rules:
	// field omitted:
	//   color is not changed
	// color: {}
	//   clears current color
	// color.id:
	//   uses existing color
	// color.code:
	//   finds existing color by code or creates new one
	Color       *CarColor `json:"color,omitempty"`
	Description *string   `json:"description,omitempty"`
	Name        *string   `json:"name,omitempty"`
}

// UpdateColorRequest defines model for UpdateColorRequest.
type UpdateColorRequest struct {
	Code *string `json:"code,omitempty"`
}

// UpdateBrandJSONRequestBody defines body for UpdateBrand for application/json ContentType.
type UpdateBrandJSONRequestBody = UpdateBrandRequest

// CreateBrandJSONRequestBody defines body for CreateBrand for application/json ContentType.
type CreateBrandJSONRequestBody = CreateBrandRequest

// CreateCarJSONRequestBody defines body for CreateCar for application/json ContentType.
type CreateCarJSONRequestBody = CreateCarRequest

// UpdateCarJSONRequestBody defines body for UpdateCar for application/json ContentType.
type UpdateCarJSONRequestBody = UpdateCarRequest

// CreateColorJSONRequestBody defines body for CreateColor for application/json ContentType.
type CreateColorJSONRequestBody = CreateColorRequest

// UpdateColorJSONRequestBody defines body for UpdateColor for application/json ContentType.
type UpdateColorJSONRequestBody = UpdateColorRequest
