// Package api_models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api_models

import (
	"time"
)

// Car defines model for Car.
type Car struct {
	CreatedAt   time.Time `json:"created_at"`
	Description *string   `json:"description,omitempty"`
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// CreateCarRequest defines model for CreateCarRequest.
type CreateCarRequest struct {
	Description *string `json:"description,omitempty"`
	Name        string  `json:"name"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Database Example: ok
	Database string `json:"database"`

	// Status Example: ok
	Status string `json:"status"`

	// Version Example: 1.0.6
	Version string `json:"version"`
}

// UpdateCarRequest defines model for UpdateCarRequest.
type UpdateCarRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// CreateCarJSONRequestBody defines body for CreateCar for application/json ContentType.
type CreateCarJSONRequestBody = CreateCarRequest

// UpdateCarJSONRequestBody defines body for UpdateCar for application/json ContentType.
type UpdateCarJSONRequestBody = UpdateCarRequest
